/*
 * adc.c
 *
 * Created: 9/9/2016 8:32:50 PM
 *  Author: Muhammad Ali
 */ 
#include "adc.h"
#include "types.h"
#include "hw_types.h"
#include "hw_adc.h"
#include <avr/interrupt.h>

static void(*adcInterrupt)(void);

uint8 init_adc(adcConfig_t *obj){
	
	HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 7 , HIGH);//enable adc module
	/* select reference voltage */
	if (obj->select_reference_voltage ==VoltageReferenceAt_AREF_pin)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 6 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 7 , LOW);
	}
	else if (obj->select_reference_voltage ==VoltageReferenceAt_AVCC_pinWithExternalCapacitorAt_AREF_pin)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 6 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 7 , LOW);
	}
	else
	{
	   HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 6 , HIGH);
	   HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 7 , HIGH);
	}
	/*select ADC channel */
	if (obj->select_ADC_channel == Single_Ended_Input_On_Channel_0_ADC0)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 0 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 1 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 2 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 3 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 4 , LOW);
	}
	else if (obj->select_ADC_channel == Single_Ended_Input_On_Channel_1_ADC1)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 0 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 1 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 2 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 3 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 4 , LOW);
	}
	else if (obj->select_ADC_channel == Single_Ended_Input_On_Channel_2_ADC2)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 0 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 1 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 2 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 3 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 4 , LOW);
	}
	else if (obj->select_ADC_channel == Single_Ended_Input_On_Channel_3_ADC3)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 0 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 1 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 2 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 3 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 4 , LOW);
	}
	else if (obj->select_ADC_channel == Single_Ended_Input_On_Channel_4_ADC4)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 0 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 1 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 2 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 3 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 4 , LOW);
	}
	else if (obj->select_ADC_channel == Single_Ended_Input_On_Channel_5_ADC5)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 0 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 1 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 2 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 3 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 4 , LOW);
	}
	else if (obj->select_ADC_channel == Single_Ended_Input_On_Channel_6_ADC6)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 0 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 1 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 2 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 3 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 4 , LOW);
	}
	else if (obj->select_ADC_channel == Single_Ended_Input_On_Channel_7_ADC7)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 0 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 1 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 2 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 3 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 4 , LOW);
	}
	#ifdef ENABLE_ADC_DIFFERENTIAL_INPUT
	
	else if (obj->select_ADC_channel == DifferentialWithGain_10x_PositiveInputOn_ADC1_NegativeInputOn_ADC0)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 0 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 1 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 2 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 3 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 4 , LOW);
	}
	
	else if (obj->select_ADC_channel == DifferentialWithGain_200x_PositiveInputOn_ADC1_NegativeInputOn_ADC0)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 0 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 1 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 2 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 3 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 4 , LOW);
	}
	
	else if (obj->select_ADC_channel == DifferentialWithGain_10x_PositiveInputOn_ADC3_NegativeInputOn_ADC2)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 0 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 1 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 2 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 3 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 4 , LOW);
	}
	
	else if (obj->select_ADC_channel == DifferentialWithGain_200x_PositiveInputOn_ADC3_NegativeInputOn_ADC2)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 0 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 1 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 2 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 3 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 4 , LOW);
	}
	else if (obj->select_ADC_channel == DifferentialWithGain_1x_PositiveInputOn_ADC0_NegativeInputOn_ADC1)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 0 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 1 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 2 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 3 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 4 , HIGH);
	}
	
	else if (obj->select_ADC_channel == DifferentialWithGain_1x_PositiveInputOn_ADC2_NegativeInputOn_ADC1)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 0 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 1 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 2 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 3 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 4 , HIGH);
	}
	else if (obj->select_ADC_channel == DifferentialWithGain_1x_PositiveInputOn_ADC3_NegativeInputOn_ADC1)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 0 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 1 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 2 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 3 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 4 , HIGH);
	}
	else if (obj->select_ADC_channel == DifferentialWithGain_1x_PositiveInputOn_ADC4_NegativeInputOn_ADC1)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 0 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 1 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 2 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 3 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 4 , HIGH);
	}
	else if (obj->select_ADC_channel == DifferentialWithGain_1x_PositiveInputOn_ADC5_NegativeInputOn_ADC1)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 0 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 1 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 2 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 3 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 4 , HIGH);
	}
	else if (obj->select_ADC_channel == DifferentialWithGain_1x_PositiveInputOn_ADC6_NegativeInputOn_ADC1)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 0 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 1 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 2 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 3 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 4 , HIGH);
	}
	else if (obj->select_ADC_channel == DifferentialWithGain_1x_PositiveInputOn_ADC7_NegativeInputOn_ADC1)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 0 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 1 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 2 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 3 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 4 , HIGH);
	}
	else if (obj->select_ADC_channel == DifferentialWithGain_1x_PositiveInputOn_ADC0_NegativeInputOn_ADC2)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 0 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 1 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 2 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 3 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 4 , HIGH);
	}
	else if (obj->select_ADC_channel == DifferentialWithGain_1x_PositiveInputOn_ADC1_NegativeInputOn_ADC2)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 0 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 1 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 2 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 3 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 4 , HIGH);
	}
	
	else if (obj->select_ADC_channel == DifferentialWithGain_1x_PositiveInputOn_ADC3_NegativeInputOn_ADC2)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 0 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 1 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 2 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 3 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 4 , HIGH);
	}
	else if (obj->select_ADC_channel == DifferentialWithGain_1x_PositiveInputOn_ADC4_NegativeInputOn_ADC2)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 0 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 1 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 2 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 3 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 4 , HIGH);
	}
	else if (obj->select_ADC_channel == DifferentialWithGain_1x_PositiveInputOn_ADC5_NegativeInputOn_ADC2)
	{
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 0 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 1 , LOW);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 2 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 3 , HIGH);
		HW_WR_BIT(ADC_MULTIPLEXER_SELECTION_REGISTER , 4 , HIGH);
	}
	#endif
	
	// select prescaler
	if (obj->select_ADC_prescaler == DivisionBy_2)
	{
		HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 0 , HIGH);
		HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 1 , LOW);
		HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 2 , LOW);
	}
	else if (obj->select_ADC_prescaler == DivisionBy_4)
	{
		HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 0 , LOW);
		HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 1 , HIGH);
		HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 2 , LOW);
	}
	else if (obj->select_ADC_prescaler == DivisionBy_8)
	{
		HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 0 , HIGH);
		HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 1 , HIGH);
		HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 2 , LOW);
	}
	else if (obj->select_ADC_prescaler == DivisionBy_16)
	{
		HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 0 , LOW);
		HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 1 , LOW);
		HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 2 , HIGH);
	}
	else if (obj->select_ADC_prescaler == DivisionBy_32)
	{
		HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 0 , HIGH);
		HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 1 , LOW);
		HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 2 , HIGH);
	}
	else if (obj->select_ADC_prescaler == DivisionBy_64)
	{
		HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 0 , LOW);
		HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 1 , HIGH);
		HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 2 , HIGH);
	}
	else if (obj->select_ADC_prescaler == DivisionBy_128)
	{
		HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 0 , HIGH);
		HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 1 , HIGH);
		HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 2 , HIGH);
	}
	else
	{
		HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 0 , LOW);
		HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 1 , LOW);
		HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 2 , LOW);
	}
	if (obj->select_AutoTrigger_source == AutoTriggerIS_Disabled)
	{
		HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 5 , LOW);  // disable auto trigger
	}
	// Auto Trigger select
	#ifdef ENABLE_AUTO_TRIGGER_SOURCE
	HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 5 , HIGH); // enable autotrigger 
	else if (obj->select_AutoTrigger_source == Free_Running_Mode)
	{
		
		HW_WR_BIT(SPECIAL_FUNCTION_INPUT_OUTPUT_REGISTER , 5 , LOW);
		HW_WR_BIT(SPECIAL_FUNCTION_INPUT_OUTPUT_REGISTER , 6 , LOW);
		HW_WR_BIT(SPECIAL_FUNCTION_INPUT_OUTPUT_REGISTER , 7 , LOW);
	}
	
	else{
		
		
		if (obj->select_AutoTrigger_source == Analog_Comparator)
		{
			HW_WR_BIT(SPECIAL_FUNCTION_INPUT_OUTPUT_REGISTER , 5 , HIGH);
			HW_WR_BIT(SPECIAL_FUNCTION_INPUT_OUTPUT_REGISTER , 6 , LOW);
			HW_WR_BIT(SPECIAL_FUNCTION_INPUT_OUTPUT_REGISTER , 7 , LOW);
		}
		else if (obj->select_AutoTrigger_source == External_Interrupt_Request_0)
		{
			HW_WR_BIT(SPECIAL_FUNCTION_INPUT_OUTPUT_REGISTER , 5 , LOW);
			HW_WR_BIT(SPECIAL_FUNCTION_INPUT_OUTPUT_REGISTER , 6 , HIGH);
			HW_WR_BIT(SPECIAL_FUNCTION_INPUT_OUTPUT_REGISTER , 7 , LOW);
		}
		else if (obj->select_AutoTrigger_source == Timer_Counter0_Compare_Match)
		{
			HW_WR_BIT(SPECIAL_FUNCTION_INPUT_OUTPUT_REGISTER , 5 , HIGH);
			HW_WR_BIT(SPECIAL_FUNCTION_INPUT_OUTPUT_REGISTER , 6 , HIGH);
			HW_WR_BIT(SPECIAL_FUNCTION_INPUT_OUTPUT_REGISTER , 7 , LOW);
		}
		else if (obj->select_AutoTrigger_source == Timer_Counter0_Overflow)
		{
			HW_WR_BIT(SPECIAL_FUNCTION_INPUT_OUTPUT_REGISTER , 5 , LOW);
			HW_WR_BIT(SPECIAL_FUNCTION_INPUT_OUTPUT_REGISTER , 6 , LOW);
			HW_WR_BIT(SPECIAL_FUNCTION_INPUT_OUTPUT_REGISTER , 7 , HIGH);
		}
		else if (obj->select_AutoTrigger_source == Timer_Counter_Compare_Match_B)
		{
			HW_WR_BIT(SPECIAL_FUNCTION_INPUT_OUTPUT_REGISTER , 5 , HIGH);
			HW_WR_BIT(SPECIAL_FUNCTION_INPUT_OUTPUT_REGISTER , 6 , LOW);
			HW_WR_BIT(SPECIAL_FUNCTION_INPUT_OUTPUT_REGISTER , 7 , HIGH);
		}
		else if (obj->select_AutoTrigger_source == Timer_Counter1_Overflow)
		{
			HW_WR_BIT(SPECIAL_FUNCTION_INPUT_OUTPUT_REGISTER , 5 , LOW);
			HW_WR_BIT(SPECIAL_FUNCTION_INPUT_OUTPUT_REGISTER , 6 , HIGH);
			HW_WR_BIT(SPECIAL_FUNCTION_INPUT_OUTPUT_REGISTER , 7 , HIGH);
		}
		else if (obj->select_AutoTrigger_source == Timer_Counter1_Capture_Event)
		{
			HW_WR_BIT(SPECIAL_FUNCTION_INPUT_OUTPUT_REGISTER , 5 , HIGH);
			HW_WR_BIT(SPECIAL_FUNCTION_INPUT_OUTPUT_REGISTER , 6 , HIGH);
			HW_WR_BIT(SPECIAL_FUNCTION_INPUT_OUTPUT_REGISTER , 7 , HIGH);
		}
	}
	#endif
	
}
//------------------------------------------------
uint8 adc_read(uint16 *data ){
	uint8 flag = 0 ;
	HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 6 , HIGH); // start conversion
	HW_RD_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A ,4 ,&flag); // read flag bit
	while(flag == 0){         // wait until conversion completes , flag = 1 when conversion completes
		HW_RD_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A ,4 ,&flag);
	}
	HW_RD_PORT(ADC_DATA_HIGH_BYTE , data);
	*data = ((*data)<<8);
	HW_RD_PORT(ADC_DATA_LOW_BYTE , data);
	return 1 ;
}

/************************************************************************/
/*                 ADC interrupt                                        */
/************************************************************************/
uint8 init_adc_interrupt(void(*adcInterruptFunctionPtr)(void)){
	HW_WR_BIT(SET_REGISTER , 7 , HIGH); // enable global interrupt
	HW_WR_BIT(ADC_CONTROL_AND_STATUS_REGISTER_A , 3 , HIGH);//enable interrupt
	adcInterrupt = adcInterruptFunctionPtr ;
}
//------------------------------------------------------------------------
ISR(ADC_vect){
	(*adcInterrupt)();
}